name: PR Extension Build

on:
  pull_request:
    paths:
      - "apps/extension/**"
      - "pnpm-lock.yaml"

jobs:
  build-extension:
    name: Build Extension and Upload Artifact
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install --filter=promptcache

      - name: Build Extension
        run: pnpm zip:extension

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-zip
          path: apps/extension/dist/*.zip
          retention-days: 5

      - name: Comment on PR with Artifact Link
        uses: actions/github-script@v7
        with:
          script: |
            const runId = process.env.GITHUB_RUN_ID;
            const artifactUrl = `https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${runId}`;

            const body = `
            **Extension build ready** 🫡

            You can download the zipped Chrome extension build [here](${artifactUrl}) from the GitHub Actions page (look for the *Artifacts* section).
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body,
            });
